# Define a BACKEND variable usable in sub-Makefiles

BACKEND := $(shell opam list --installed --short mirage-xen)

ifeq ($(strip $(BACKEND)),mirage-xen)
	BACKEND := --xen
else
	BACKEND := --unix
endif
