# Define a BACKEND variable usable in sub-Makefiles

BACKEND := $(shell opam list --installed --short mirage-xen)

ifeq ($(strip $(BACKEND)),mirage-xen)
	BACKEND := --xen
else
	BACKEND := --unix
endif

.PHONY: all clean

all: build
	@

src/dist/setup:
	mirari configure $(BACKEND)

build: src/dist/setup
	mirari build $(BACKEND)

run:
	mirari run $(BACKEND)

clean:
	mirari clean
