MIRAGE    = mirage
OPAM      = opam
LOCK      = ./mirage.opam.locked

# Note that the mirage tool interprets overlays like: <name>:<url>(','<name>:<url>)+

OVERLAYS ?= opam-overlays:https://github.com/dune-universe/opam-overlays.git \
            mirage-opam-overlays:https://github.com/dune-universe/mirage-opam-overlays.git
MODE     ?= unix
NET      ?= socket

MIRAGE_FLAGS ?=
