MIRAGE    = mirage
OPAM      = opam
LOCK      = ./mirage.opam.locked

MIRAGE_EXTRA_REPOS ?= opam-overlays:https://github.com/dune-universe/opam-overlays.git,\
                      mirage-opam-overlays:https://github.com/dune-universe/mirage-opam-overlays.git
MODE     ?= unix
NET      ?= socket

MIRAGE_FLAGS ?=
